.PHONY: download_data download_description

download_data:
	curl -O http://www.stat.ufl.edu/~winner/data/cyclone.dat

download_description:
	curl -O http://www.stat.ufl.edu/~winner/data/cyclone.txt

download_all:
	make download_data
	make download_description
